name: Deploy Admin Dashboard to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/ludo-game-project/ludo-game-admin-dashboard
            cd ~/ludo-game-project/ludo-game-admin-dashboard

            if [ ! -d ".git" ]; then
              git clone https://github.com/Aqdas34/dream-ludo-admin-dashboard.git .
            else
              git pull origin master
            fi

            printf "%s" "${{ secrets.PROJECT_ENV }}" > .env

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            npm install
            npm run build

            pm2 delete ludo-admin-dashboard || true
            pm2 start "npx vite preview --host 0.0.0.0 --port 3006" --name ludo-admin-dashboard
            pm2 save
